server:
  port: 6002
  # 服务端口
eureka:
  server:
    enable-self-preservation: false # 禁用自我保护模式
  instance:
    hostname: eureka6002.com # eureka服务端的实例名称
  client:
    registerWithEureka: false # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: false # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自 己（如果不配置则默认本机8761端口）
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    多个配置
#    defaultZone: http://eureka6002.com:6002/eureka/,http://eureka6002.com:6002/eureka/
      defaultZone: http://eureka6001.com:6001/eureka/